import { createContext, useContext, useMemo, useState } from 'react';

const LanguageContext = createContext(null);
const LANGUAGE_KEY = 'house_language';

const translations = {
  uk: {
    showPassword: 'Показати пароль',
    hidePassword: 'Сховати пароль',
    restoringSession: 'Відновлення сеансу',
    password: 'Пароль',
    currentPassword: 'Поточний пароль',
    newPassword: 'Новий пароль',
    confirmNewPassword: 'Повторіть новий пароль',
    changePasswordTitle: 'Змініть пароль',
    changePasswordSubtitle: 'Для продовження потрібен новий пароль.',
    changePasswordButton: 'Змінити пароль',
    saving: 'Збереження',
    signIn: 'Увійти',
    signingIn: 'Вхід',
    rememberSession: "Запам'ятати сеанс",
    loginSubtitle: 'Прототип керування житловим будинком',
    adminDemoCredentials: 'Адміністратор: admin@house.com / Admin123!',
    residentDemoCredentials: 'Мешканець: resident@house.com / Resident123!',
    prototypeSecurityNotice: 'ISO/IEC 27001-inspired controls are implemented for prototype purposes only.',
    validEmailRequired: 'Введіть коректну email-адресу.',
    strongPasswordRequired: 'Використайте щонайменше 8 символів: велику й малу літеру, цифру та символ.',
    currentPasswordRequired: 'Поточний пароль обовʼязковий.',
    passwordsMustMatch: 'Паролі мають збігатися.',
    passwordChangeFailed: 'Не вдалося змінити пароль.',
    language: 'Мова',
    switchLanguage: 'Перемкнути мову',
    appName: 'Дім Онлайн',
    logout: 'Вийти',
    adminRole: 'Адміністратор',
    residentRole: 'Мешканець',
    lastLogin: 'Останній вхід',
    navAdminDashboard: 'Панель адміністратора',
    navResidentHome: 'Головна мешканця',
    navMyRequests: 'Мої заявки',
    navMyPayments: 'Мої платежі',
    navPaymentsOverview: 'Огляд платежів',
    navAuditLog: 'Журнал аудиту',
    navSecurityIncidents: 'Інциденти безпеки',
    navBuildingContacts: 'Контакти будинку',
    navDashboard: 'Панель адміністратора',
    navResidents: 'Мешканці',
    navAnnouncements: 'Оголошення',
    navMaintenance: 'Заявки',
    navPayments: 'Огляд платежів',
    navAudit: 'Журнал аудиту',
    navIncidents: 'Інциденти безпеки',
    navContacts: 'Контакти',
    navHome: 'Головна мешканця',
    navProfile: 'Профіль',
    refresh: 'Оновити',
    residentsTitle: 'Мешканці',
    name: 'Імʼя',
    email: 'Email',
    temporaryPassword: 'Тимчасовий пароль',
    residentPhone: 'Телефон мешканця',
    apartment: 'Квартира',
    noApartment: 'Без квартири',
    apartmentStatusOccupied: 'зайнята',
    apartmentStatusVacant: 'вільна',
    apartmentStatusMaintenance: 'ремонт',
    emergencyContactPerson: 'Контактна особа для екстрених випадків',
    emergencyContactPhone: 'Телефон екстреного контакту',
    adminNotes: 'Адміністративні нотатки',
    active: 'Активний',
    disabled: 'Вимкнений',
    mustChangePassword: 'Потрібна зміна пароля',
    passwordUpdated: 'Пароль оновлено',
    saveResident: 'Зберегти мешканця',
    addResident: 'Додати мешканця',
    cancel: 'Скасувати',
    edit: 'Редагувати',
    deactivate: 'Деактивувати',
    deactivating: 'Вимкнення...',
    residentCreatedTemporaryPassword: 'Мешканця створено. Передайте йому тимчасовий пароль, який ви вказали.',
    residentUpdated: 'Мешканця оновлено.',
    residentDeactivated: 'Мешканця деактивовано.',
    residentsLoadFailed: 'Не вдалося завантажити мешканців.',
    noResidents: 'Мешканців ще не додано.',
    residentSaveFailed: 'Не вдалося зберегти мешканця.',
    residentDeactivateFailed: 'Не вдалося деактивувати мешканця.',
    nameRequired: 'Імʼя обовʼязкове.',
    nameTooLong: 'Імʼя має містити не більше 120 символів.',
    emailInvalid: 'Потрібен коректний email.',
    temporaryPasswordWeak: 'Тимчасовий пароль має містити 8+ символів, великі/малі літери, цифру і спецсимвол.',
    residentPhoneTooLong: 'Телефон мешканця має містити не більше 40 символів.',
    residentPhoneInvalid: 'Введіть телефон у форматі +38(067)-123-45-67.',
    emergencyContactTooLong: 'Контактна особа має містити не більше 120 символів.',
    emergencyPhoneTooLong: 'Телефон екстреного контакту має містити не більше 40 символів.',
    emergencyPhoneInvalid: 'Введіть телефон екстреного контакту у форматі +38(067)-123-45-67.',
    notesTooLong: 'Нотатки мають містити не більше 1000 символів.',
    profileTitle: 'Профіль',
    yourPhoneNumber: 'Ваш номер телефону',
    profileLoadFailed: 'Не вдалося завантажити профіль.',
    profileSaved: 'Профіль оновлено.',
    profileSaveFailed: 'Не вдалося зберегти профіль.',
    notProvided: 'Не вказано',
    notAssigned: 'Не призначена',
    avatarLater: 'Завантаження аватара буде додано на окремому етапі. Зараз backend зберігає тільки шлях до аватара.',
    saveProfile: 'Зберегти профіль',
    myRequests: 'Мої заявки',
    title: 'Заголовок',
    category: 'Категорія',
    details: 'Опис',
    submitRequest: 'Надіслати заявку',
    sending: 'Надсилання',
    requestSent: 'Заявку на обслуговування надіслано.',
    noRequests: 'Заявок на обслуговування поки немає.',
    requestsLoadFailed: 'Не вдалося завантажити заявки.',
    requestSaveFailed: 'Не вдалося зберегти заявку.',
    adminResponse: 'Відповідь адміністратора',
    internalNotes: 'Внутрішні нотатки',
    priority: 'Пріоритет',
    status: 'Статус',
    createdAt: 'Створено',
    updatedAt: 'Оновлено',
    resolvedAt: 'Вирішено',
    statusNew: 'Нова',
    statusWaitingResident: 'Очікує мешканця',
    statusCancelled: 'Скасовано',
    priorityLow: 'Низький',
    priorityNormal: 'Звичайний',
    priorityHigh: 'Високий',
    priorityUrgent: 'Терміновий',
    all: 'Усі',
    search: 'Пошук',
    applyFilters: 'Застосувати',
    updateRequest: 'Оновити заявку',
    requestUpdated: 'Заявку оновлено.',
    selectRequest: 'Виберіть заявку для редагування.',
    resident: 'Мешканець',
    titleRequired: 'Заголовок обовʼязковий.',
    categoryRequired: 'Категорія обовʼязкова.',
    detailsRequired: 'Опис обовʼязковий.',
    detailsTooLong: 'Опис має містити не більше 3000 символів.',
    adminDashboardTitle: 'Панель адміністратора',
    residentHomeTitle: 'Головна мешканця',
    myPaymentsTitle: 'Мої платежі',
    paymentsOverviewTitle: 'Огляд платежів',
    paymentsLoadFailed: 'Не вдалося завантажити платежі.',
    paymentSaveFailed: 'Не вдалося зберегти платіж.',
    noPayments: 'Платежів поки немає.',
    createPayment: 'Створити платіж',
    updatePayment: 'Оновити платіж',
    paymentSaved: 'Платіж збережено.',
    amount: 'Сума',
    dueDate: 'Дата оплати',
    paidAt: 'Сплачено',
    period: 'Період',
    periodYear: 'Рік',
    periodMonth: 'Місяць',
    paymentType: 'Тип платежу',
    titleUk: 'Заголовок UK',
    titleEn: 'Заголовок EN',
    descriptionUk: 'Опис UK',
    descriptionEn: 'Опис EN',
    selectPayment: 'Виберіть платіж для редагування.',
    markPaid: 'Позначити сплаченим',
    cancelPayment: 'Скасувати платіж',
    paymentStatusPending: 'Очікує',
    paymentStatusPaid: 'Сплачено',
    paymentStatusOverdue: 'Прострочено',
    paymentStatusCancelled: 'Скасовано',
    paymentTypeRent: 'Оренда',
    paymentTypeUtilities: 'Комунальні',
    paymentTypeMaintenance: 'Обслуговування',
    paymentTypeSecurity: 'Охорона',
    paymentTypeParking: 'Паркування',
    paymentTypeOther: 'Інше',
    amountInvalid: 'Введіть суму більше 0 у форматі 1250.00.',
    announcementsTitle: 'Оголошення',
    auditLogTitle: 'Журнал аудиту',
    securityIncidentsTitle: 'Інциденти безпеки',
    auditLoadFailed: 'Не вдалося завантажити журнал аудиту.',
    auditAction: 'Дія',
    auditEntityType: 'Тип сутності',
    allActions: 'Усі дії',
    allEntities: 'Усі сутності',
    dateFrom: 'Дата від',
    dateTo: 'Дата до',
    auditEmpty: 'Записів аудиту за цими фільтрами немає.',
    systemActor: 'Система',
    auditActionLOGIN_SUCCESS: 'Успішний вхід',
    auditActionLOGIN_FAILED: 'Невдалий вхід',
    auditActionLOGOUT: 'Вихід',
    auditActionPASSWORD_CHANGED: 'Пароль змінено',
    auditActionRESIDENT_CREATED: 'Мешканця створено',
    auditActionRESIDENT_UPDATED: 'Мешканця оновлено',
    auditActionRESIDENT_DEACTIVATED: 'Мешканця деактивовано',
    auditActionAPARTMENT_CREATED: 'Квартиру створено',
    auditActionAPARTMENT_UPDATED: 'Квартиру оновлено',
    auditActionANNOUNCEMENT_CREATED: 'Оголошення створено',
    auditActionANNOUNCEMENT_PUBLISHED: 'Оголошення опубліковано',
    auditActionANNOUNCEMENT_ARCHIVED: 'Оголошення архівовано',
    auditActionCONTACT_CREATED: 'Контакт створено',
    auditActionCONTACT_UPDATED: 'Контакт оновлено',
    auditActionCONTACT_DEACTIVATED: 'Контакт деактивовано',
    auditActionMAINTENANCE_CREATED: 'Заявку створено',
    auditActionMAINTENANCE_UPDATED: 'Заявку оновлено',
    auditActionPAYMENT_CREATED: 'Платіж створено',
    auditActionPAYMENT_UPDATED: 'Платіж оновлено',
    auditActionPAYMENT_STATUS_CHANGED: 'Статус платежу змінено',
    auditActionPAYMENT_CANCELLED: 'Платіж скасовано',
    auditActionSECURITY_INCIDENT_CREATED: 'Інцидент створено',
    auditActionSECURITY_INCIDENT_UPDATED: 'Інцидент оновлено',
    auditActionSECURITY_INCIDENT_RESOLVED: 'Інцидент закрито',
    auditEntityAUTH: 'Автентифікація',
    auditEntityUSER: 'Користувач',
    auditEntityRESIDENT: 'Мешканець',
    auditEntityAPARTMENT: 'Квартира',
    auditEntityANNOUNCEMENT: 'Оголошення',
    auditEntityCONTACT: 'Контакт',
    auditEntityMAINTENANCE_REQUEST: 'Заявка',
    auditEntityPAYMENT: 'Платіж',
    auditEntitySECURITY_INCIDENT: 'Інцидент безпеки',
    auditEntitySYSTEM: 'Система',
    severity: 'Критичність',
    assignedTo: 'Призначено',
    assignedToUserId: 'ID відповідального',
    relatedAuditLogId: 'ID запису аудиту',
    resolutionNotes: 'Нотатки рішення',
    incidentsLoadFailed: 'Не вдалося завантажити інциденти.',
    incidentSaved: 'Інцидент збережено.',
    incidentSaveFailed: 'Не вдалося зберегти інцидент.',
    createIncident: 'Створити інцидент',
    updateIncident: 'Оновити інцидент',
    allSeverities: 'Усі критичності',
    allStatuses: 'Усі статуси',
    allCategories: 'Усі категорії',
    incidentsEmpty: 'Інцидентів за цими фільтрами немає.',
    incidentSeverityLOW: 'Низька',
    incidentSeverityMEDIUM: 'Середня',
    incidentSeverityHIGH: 'Висока',
    incidentSeverityCRITICAL: 'Критична',
    incidentStatusOPEN: 'Відкрито',
    incidentStatusINVESTIGATING: 'Розслідується',
    incidentStatusRESOLVED: 'Вирішено',
    incidentStatusFALSE_POSITIVE: 'Хибне спрацювання',
    incidentCategoryAUTHENTICATION: 'Автентифікація',
    incidentCategoryAUTHORIZATION: 'Авторизація',
    incidentCategoryDATA_ACCESS: 'Доступ до даних',
    incidentCategoryPAYMENT: 'Платежі',
    incidentCategoryMAINTENANCE: 'Заявки',
    incidentCategorySYSTEM: 'Система',
    incidentCategoryOTHER: 'Інше',
    markInvestigating: 'Розслідувати',
    markResolved: 'Позначити вирішеним',
    markFalsePositive: 'Хибне спрацювання',
    incidentResolvedNote: 'Інцидент вирішено адміністратором.',
    buildingContactsTitle: 'Контакти будинку',
    contactsTitle: 'Контакти',
    maintenanceTitle: 'Заявки',
    unknownResident: 'Невідомий мешканець',
    sectionLabel: 'Секція',
    apartmentShort: 'кв.',
    floorLabel: 'поверх',
    apartmentNotAssigned: 'Квартира не призначена',
    statusOpen: 'Відкрито',
    statusInProgress: 'У роботі',
    statusResolved: 'Вирішено',
    statusRejected: 'Відхилено',
    plumbing: 'Сантехніка',
    electricity: 'Електрика',
    heating: 'Опалення',
    internet: 'Інтернет',
    elevator: 'Ліфт',
    cleaning: 'Прибирання',
    security: 'Безпека',
    other: 'Інше',
  },
  en: {
    showPassword: 'Show password',
    hidePassword: 'Hide password',
    restoringSession: 'Restoring session',
    password: 'Password',
    currentPassword: 'Current password',
    newPassword: 'New password',
    confirmNewPassword: 'Repeat new password',
    changePasswordTitle: 'Change password',
    changePasswordSubtitle: 'A new password is required to continue.',
    changePasswordButton: 'Change password',
    saving: 'Saving',
    signIn: 'Sign in',
    signingIn: 'Signing in',
    rememberSession: 'Remember session',
    loginSubtitle: 'Residential building management prototype',
    adminDemoCredentials: 'Administrator: admin@house.com / Admin123!',
    residentDemoCredentials: 'Resident: resident@house.com / Resident123!',
    prototypeSecurityNotice: 'ISO/IEC 27001-inspired controls are implemented for prototype purposes only.',
    validEmailRequired: 'Enter a valid email address.',
    strongPasswordRequired: 'Use at least 8 characters: uppercase, lowercase, digit, and symbol.',
    currentPasswordRequired: 'Current password is required.',
    passwordsMustMatch: 'Passwords must match.',
    passwordChangeFailed: 'Could not change password.',
    language: 'Language',
    switchLanguage: 'Switch language',
    appName: 'House Online',
    logout: 'Logout',
    adminRole: 'Administrator',
    residentRole: 'Resident',
    lastLogin: 'Last login',
    navAdminDashboard: 'Admin Dashboard',
    navResidentHome: 'Resident Home',
    navMyRequests: 'My Requests',
    navMyPayments: 'My Payments',
    navPaymentsOverview: 'Payments Overview',
    navAuditLog: 'Audit Log',
    navSecurityIncidents: 'Security Incidents',
    navBuildingContacts: 'Building Contacts',
    navDashboard: 'Admin Dashboard',
    navResidents: 'Residents',
    navAnnouncements: 'Announcements',
    navMaintenance: 'Requests',
    navPayments: 'Payments Overview',
    navAudit: 'Audit Log',
    navIncidents: 'Security Incidents',
    navContacts: 'Contacts',
    navHome: 'Resident Home',
    navProfile: 'Profile',
    refresh: 'Refresh',
    residentsTitle: 'Residents',
    name: 'Name',
    email: 'Email',
    temporaryPassword: 'Temporary password',
    residentPhone: 'Resident phone',
    apartment: 'Apartment',
    noApartment: 'No apartment',
    apartmentStatusOccupied: 'occupied',
    apartmentStatusVacant: 'vacant',
    apartmentStatusMaintenance: 'maintenance',
    emergencyContactPerson: 'Emergency contact person',
    emergencyContactPhone: 'Emergency contact phone',
    adminNotes: 'Administrative notes',
    active: 'Active',
    disabled: 'Disabled',
    mustChangePassword: 'Password change required',
    passwordUpdated: 'Password updated',
    saveResident: 'Save resident',
    addResident: 'Add resident',
    cancel: 'Cancel',
    edit: 'Edit',
    deactivate: 'Deactivate',
    deactivating: 'Deactivating...',
    residentCreatedTemporaryPassword: 'Resident created. Give them the temporary password you entered.',
    residentUpdated: 'Resident updated.',
    residentDeactivated: 'Resident deactivated.',
    residentsLoadFailed: 'Could not load residents.',
    noResidents: 'No residents yet.',
    residentSaveFailed: 'Could not save resident.',
    residentDeactivateFailed: 'Could not deactivate resident.',
    nameRequired: 'Name is required.',
    nameTooLong: 'Name must be 120 characters or fewer.',
    emailInvalid: 'A valid email is required.',
    temporaryPasswordWeak: 'Temporary password must contain 8+ characters, uppercase, lowercase, digit, and special character.',
    residentPhoneTooLong: 'Resident phone must be 40 characters or fewer.',
    residentPhoneInvalid: 'Enter the phone number as +38(067)-123-45-67.',
    emergencyContactTooLong: 'Emergency contact person must be 120 characters or fewer.',
    emergencyPhoneTooLong: 'Emergency contact phone must be 40 characters or fewer.',
    emergencyPhoneInvalid: 'Enter the emergency contact phone as +38(067)-123-45-67.',
    notesTooLong: 'Notes must be 1000 characters or fewer.',
    profileTitle: 'Profile',
    yourPhoneNumber: 'Your phone number',
    profileLoadFailed: 'Could not load profile.',
    profileSaved: 'Profile updated.',
    profileSaveFailed: 'Could not save profile.',
    notProvided: 'Not provided',
    notAssigned: 'Not assigned',
    avatarLater: 'Avatar upload will be added in a later stage. The backend stores only the avatar path for now.',
    saveProfile: 'Save profile',
    myRequests: 'My requests',
    title: 'Title',
    category: 'Category',
    details: 'Details',
    submitRequest: 'Submit request',
    sending: 'Sending',
    requestSent: 'Maintenance request sent.',
    noRequests: 'No maintenance requests yet.',
    requestsLoadFailed: 'Could not load requests.',
    requestSaveFailed: 'Could not save request.',
    adminResponse: 'Admin response',
    internalNotes: 'Internal notes',
    priority: 'Priority',
    status: 'Status',
    createdAt: 'Created',
    updatedAt: 'Updated',
    resolvedAt: 'Resolved',
    statusNew: 'New',
    statusWaitingResident: 'Waiting for resident',
    statusCancelled: 'Cancelled',
    priorityLow: 'Low',
    priorityNormal: 'Normal',
    priorityHigh: 'High',
    priorityUrgent: 'Urgent',
    all: 'All',
    search: 'Search',
    applyFilters: 'Apply',
    updateRequest: 'Update request',
    requestUpdated: 'Request updated.',
    selectRequest: 'Select a request to edit.',
    resident: 'Resident',
    titleRequired: 'Title is required.',
    categoryRequired: 'Category is required.',
    detailsRequired: 'Details are required.',
    detailsTooLong: 'Details must be 3000 characters or fewer.',
    adminDashboardTitle: 'Admin Dashboard',
    residentHomeTitle: 'Resident Home',
    myPaymentsTitle: 'My Payments',
    paymentsOverviewTitle: 'Payments Overview',
    paymentsLoadFailed: 'Could not load payments.',
    paymentSaveFailed: 'Could not save payment.',
    noPayments: 'No payments yet.',
    createPayment: 'Create payment',
    updatePayment: 'Update payment',
    paymentSaved: 'Payment saved.',
    amount: 'Amount',
    dueDate: 'Due date',
    paidAt: 'Paid',
    period: 'Period',
    periodYear: 'Year',
    periodMonth: 'Month',
    paymentType: 'Payment type',
    titleUk: 'Title UK',
    titleEn: 'Title EN',
    descriptionUk: 'Description UK',
    descriptionEn: 'Description EN',
    selectPayment: 'Select a payment to edit.',
    markPaid: 'Mark paid',
    cancelPayment: 'Cancel payment',
    paymentStatusPending: 'Pending',
    paymentStatusPaid: 'Paid',
    paymentStatusOverdue: 'Overdue',
    paymentStatusCancelled: 'Cancelled',
    paymentTypeRent: 'Rent',
    paymentTypeUtilities: 'Utilities',
    paymentTypeMaintenance: 'Maintenance',
    paymentTypeSecurity: 'Security',
    paymentTypeParking: 'Parking',
    paymentTypeOther: 'Other',
    amountInvalid: 'Enter an amount greater than 0 as 1250.00.',
    announcementsTitle: 'Announcements',
    auditLogTitle: 'Audit Log',
    securityIncidentsTitle: 'Security Incidents',
    auditLoadFailed: 'Could not load audit logs.',
    auditAction: 'Action',
    auditEntityType: 'Entity type',
    allActions: 'All actions',
    allEntities: 'All entities',
    dateFrom: 'Date from',
    dateTo: 'Date to',
    auditEmpty: 'No audit records match these filters.',
    systemActor: 'System',
    auditActionLOGIN_SUCCESS: 'Login success',
    auditActionLOGIN_FAILED: 'Login failed',
    auditActionLOGOUT: 'Logout',
    auditActionPASSWORD_CHANGED: 'Password changed',
    auditActionRESIDENT_CREATED: 'Resident created',
    auditActionRESIDENT_UPDATED: 'Resident updated',
    auditActionRESIDENT_DEACTIVATED: 'Resident deactivated',
    auditActionAPARTMENT_CREATED: 'Apartment created',
    auditActionAPARTMENT_UPDATED: 'Apartment updated',
    auditActionANNOUNCEMENT_CREATED: 'Announcement created',
    auditActionANNOUNCEMENT_PUBLISHED: 'Announcement published',
    auditActionANNOUNCEMENT_ARCHIVED: 'Announcement archived',
    auditActionCONTACT_CREATED: 'Contact created',
    auditActionCONTACT_UPDATED: 'Contact updated',
    auditActionCONTACT_DEACTIVATED: 'Contact deactivated',
    auditActionMAINTENANCE_CREATED: 'Request created',
    auditActionMAINTENANCE_UPDATED: 'Request updated',
    auditActionPAYMENT_CREATED: 'Payment created',
    auditActionPAYMENT_UPDATED: 'Payment updated',
    auditActionPAYMENT_STATUS_CHANGED: 'Payment status changed',
    auditActionPAYMENT_CANCELLED: 'Payment cancelled',
    auditActionSECURITY_INCIDENT_CREATED: 'Incident created',
    auditActionSECURITY_INCIDENT_UPDATED: 'Incident updated',
    auditActionSECURITY_INCIDENT_RESOLVED: 'Incident closed',
    auditEntityAUTH: 'Authentication',
    auditEntityUSER: 'User',
    auditEntityRESIDENT: 'Resident',
    auditEntityAPARTMENT: 'Apartment',
    auditEntityANNOUNCEMENT: 'Announcement',
    auditEntityCONTACT: 'Contact',
    auditEntityMAINTENANCE_REQUEST: 'Request',
    auditEntityPAYMENT: 'Payment',
    auditEntitySECURITY_INCIDENT: 'Security incident',
    auditEntitySYSTEM: 'System',
    severity: 'Severity',
    assignedTo: 'Assigned to',
    assignedToUserId: 'Assignee user ID',
    relatedAuditLogId: 'Audit log ID',
    resolutionNotes: 'Resolution notes',
    incidentsLoadFailed: 'Could not load incidents.',
    incidentSaved: 'Incident saved.',
    incidentSaveFailed: 'Could not save incident.',
    createIncident: 'Create incident',
    updateIncident: 'Update incident',
    allSeverities: 'All severities',
    allStatuses: 'All statuses',
    allCategories: 'All categories',
    incidentsEmpty: 'No incidents match these filters.',
    incidentSeverityLOW: 'Low',
    incidentSeverityMEDIUM: 'Medium',
    incidentSeverityHIGH: 'High',
    incidentSeverityCRITICAL: 'Critical',
    incidentStatusOPEN: 'Open',
    incidentStatusINVESTIGATING: 'Investigating',
    incidentStatusRESOLVED: 'Resolved',
    incidentStatusFALSE_POSITIVE: 'False positive',
    incidentCategoryAUTHENTICATION: 'Authentication',
    incidentCategoryAUTHORIZATION: 'Authorization',
    incidentCategoryDATA_ACCESS: 'Data access',
    incidentCategoryPAYMENT: 'Payment',
    incidentCategoryMAINTENANCE: 'Maintenance',
    incidentCategorySYSTEM: 'System',
    incidentCategoryOTHER: 'Other',
    markInvestigating: 'Investigate',
    markResolved: 'Mark resolved',
    markFalsePositive: 'False positive',
    incidentResolvedNote: 'Incident resolved by administrator.',
    buildingContactsTitle: 'Building Contacts',
    contactsTitle: 'Contacts',
    maintenanceTitle: 'Requests',
    unknownResident: 'Unknown resident',
    sectionLabel: 'Section',
    apartmentShort: 'apt.',
    floorLabel: 'floor',
    apartmentNotAssigned: 'Apartment is not assigned',
    statusOpen: 'Open',
    statusInProgress: 'In progress',
    statusResolved: 'Resolved',
    statusRejected: 'Rejected',
    plumbing: 'Plumbing',
    electricity: 'Electricity',
    heating: 'Heating',
    internet: 'Internet',
    elevator: 'Elevator',
    cleaning: 'Cleaning',
    security: 'Security',
    other: 'Other',
  },
};

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => {
    const stored = localStorage.getItem(LANGUAGE_KEY);
    return stored === 'en' ? 'en' : 'uk';
  });

  const setLanguage = (nextLanguage) => {
    const normalized = nextLanguage === 'en' ? 'en' : 'uk';
    localStorage.setItem(LANGUAGE_KEY, normalized);
    setLanguageState(normalized);
  };

  const t = (key) => translations[language][key] || translations.uk[key] || key;

  const value = useMemo(() => ({ language, setLanguage, t }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export const useLanguage = () => useContext(LanguageContext);
