package com.houseapp.entity;

public enum AuditAction {
  LOGIN_SUCCESS,
  LOGIN_FAILED,
  LOGOUT,
  PASSWORD_CHANGED,
  RESIDENT_CREATED,
  RESIDENT_UPDATED,
  RESIDENT_DEACTIVATED,
  APARTMENT_CREATED,
  APARTMENT_UPDATED,
  ANNOUNCEMENT_CREATED,
  ANNOUNCEMENT_PUBLISHED,
  ANNOUNCEMENT_ARCHIVED,
  CONTACT_CREATED,
  CONTACT_UPDATED,
  CONTACT_DEACTIVATED,
  MAINTENANCE_CREATED,
  MAINTENANCE_UPDATED,
  PAYMENT_CREATED,
  PAYMENT_UPDATED,
  PAYMENT_STATUS_CHANGED,
  PAYMENT_CANCELLED,
  SECURITY_INCIDENT_CREATED,
  SECURITY_INCIDENT_UPDATED,
  SECURITY_INCIDENT_RESOLVED
}
